import type { Metadata } from "next";
import LocalFont from "next/font/local";
import "./globals.css";
import React from "react";

const inter = LocalFont({
  src: "./fonts/InterVF.ttf",
  variable: "--font-inter",
  weight: " 300 400 500 600 700 ",
});
const spacegrotesk = LocalFont({
  src: "./fonts/SpaceGroteskVF.ttf",
  variable: "--font-space-grotesk",
  weight: "100 200 300 400 500 600 700 800 900",
});

export const metadata: Metadata = {
  title: "Dev Overflow",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} ${spacegrotesk.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
